sudo: required
dist: trusty
language: cpp
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
    
before_install:
    - gcc --version
    - cmake --version
    - if [[ $TRAVIS_OS_NAME == linux && `cmake --version | awk -F' ' '{print $3}'` < '3.2.2' ]]; then chmod +x ./scripts/before_install_ubuntu.sh && ./scripts/before_install_ubuntu.sh; fi

addons: &addons
    apt:
        sources: &sources
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team
        packages:
            - gcc-5
            - g++-5
            - libstdc++-5-dev
before_script:
    - |
        case "$CXX" in #(
        g++*) CXX=g++-5 #(
        ;;
        esac
    - |
        case "$CC" in #(
        gcc*) CC=gcc-5 #(
        ;;
        esac
    - export CXX CC
    - mkdir -p build && cd build && cmake .. 
script:
    - make -j8 
    - ./r-value_reference/r-value_reference
    
