# use ubuntu-14.4
sudo: required
dist: trusty

language: cpp
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
    
before_install:
    - cmake --version
    - sudo apt-get remove gcc # 卸载旧版本
    - if [[ $TRAVIS_OS_NAME == linux && `cmake --version | awk -F' ' '{print $3}'` < '3.2.2' ]]; then chmod +x ./scripts/before_install_ubuntu.sh && ./scripts/before_install_ubuntu.sh; fi

addons: &addons
    apt:
        sources: &sources
            - ubuntu-toolchain-r-test
            - ubuntu-sdk-team
        packages:
            - cmake
            - g++-5
            - libstdc++-5-dev
before_script:
    # - |
        # if [ $TRAVIS_OS_NAME = linux ]; then
            # case "$CXX" in #(
            # g++*) CXX=g++-5
            # ;;
            # esac
        # fi
    # - |
        # if [ $TRAVIS_OS_NAME = linux ]; then
            # case "$CC" in #(
                # gcc*) CC=gcc-5
                # ;;
            # esac
        # fi
    # - if [ $TRAVIS_OS_NAME = linux ]; then export CXX CC; fi
    - $CXX --version && $CC --version && cmake --version
    - mkdir -p build && cd build && cmake .. 
script:
    - make -j8 
    - ./r-value_reference/r-value_reference
    
