sudo: false
language: cpp
os:
    - linux
    - osx
compiler:
    - clang
    - gcc
before_script:
    - mkdir -p build && cd build && cmake .. 
script:
    - make -j8 
    - ./r-value_reference/r-value_reference
    
